[package]
name = "advent-of-code-2020"
version = "0.1.0"
authors = ["Clayton Ferris <cferris@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5.5"
peg = "0.6.3"
itertools = "0.9.0"